<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Game;
use AppBundle\Entity\Player;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextForUser(Player $player, Game $game)
    {
        return $this->createQueryBuilder('a')
            ->where("a.response = ''")
            ->andWhere('a.player = :player')
            ->andWhere('a.game = :game')
            ->orderBy('a.id', 'asc')
            ->setParameters([
                'player' => $player,
                'game' => $game
            ])
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
