<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Game;
use AppBundle\Entity\Player;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPlayer(Player $player)
    {
        return $this->createQueryBuilder('g')
            ->join('g.players', 'p')
            ->where('p.id = :player')
            ->getQuery()
            ->setParameters([
                'player' => $player
            ])
            ->getOneOrNullResult()
        ;
    }
    
    public function findCurrentGameForPlayer(Player $player, $state = null)
    {
        /** @var Game $game */
        $query = $this->createQueryBuilder('g')
            ->join('g.players', 'p')
            ->andWhere('p.id = :player')
            ->andWhere("g.state != 'end'")
        ;
        if ($state !== null) {
            $query = $query
                ->andWhere('g.state = :state')
                ->setParameter('state', $state)
            ;
        }
        
        $game = $query
            ->orderBy('g.id', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->setParameter('player', $player->getId())
            ->getOneOrNullResult()
        ;
        
        return $game;
    }
    
    public function findRunningGames($chatGroup)
    {
         /** @var Game $game */
        return $this->createQueryBuilder('g')
            ->andWhere("g.state != 'end'")
            ->andWhere('g.chatGroup = :chatGroup')
            ->getQuery()
            ->setParameter('chatGroup', $chatGroup)
            ->execute()
        ;
    }
}
