<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function generateQuestions($playerCount)
    {
        $questions = $this->findBy([],null);
        shuffle($questions);
        return array_slice($questions, 0, $playerCount);
    }
}
