<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Question;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function generateQuestions($userCount)
    {
        $questions = $this->findBy([],null);
        shuffle($questions);
        return array_slice($questions, 0, $userCount);
    }

    /**
     * @param $existingQuestions
     * @return Question
     */
    public function getTieBreakerQuestion($existingQuestions)
    {
        $possibleQuestions = $this
            ->createQueryBuilder('q')
            ->where('q.id NOT IN (:questions)')
            ->setParameter('questions', $existingQuestions)
            ->getQuery()
            ->execute()
        ;

        shuffle($possibleQuestions);
        return reset($possibleQuestions);
    }
}
