imports:
    - { resource: config.yml }
    - { resource: parameters_prod.php }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        graylog:
            type: gelf
            publisher:
                id: app.graylog.publisher
            level: debug
            channels: ['app']
        main:
            type: error_log
            level: debug
            channels: ['!event']
