imports:
    - { resource: config.yml }
    - { resource: parameters_prod.php }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: error_log
        console:
            type: console
            process_psr_3_messages: false
