imports:
    - { resource: config.yml }
    - { resource: parameters_prod.php }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

services:
    app.logdna.handler:
        class: Zwijn\Monolog\Handler\LogdnaHandler
        arguments:
            - '%logdna_token%'
            - 'quiplash_telegram_bot'

monolog:
    handlers:
        logdna:
            type: service
            id: app.logdna.handler
            channels: ['app']
        main:
            type: error_log
            level: debug
            channels: ['!event']
