imports:
    - { resource: config_dev.yml }

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%_test'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
