imports:
    - { resource: config_dev.yml }

services:
    telegram_client:
        class: AppBundle\StubClient
        arguments:
            - '@logger'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%kernel.project_dir%/var/data/data_test.sqlite"
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
    test: ~
    csrf_protection:
        enabled: false
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
