# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        chain_provider:
            chain:
                providers:
                    - entity_provider
                    - telegram_update
        entity_provider:
            entity:
                class: AppBundle:User
        telegram_update:
            id: 'AppBundle\Security\TelegramUpdateUserProvider'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        prompt:
            pattern: ^/telegram/quiplash/prompts
            security: false
            stateless: true

        main:
            pattern: ^/
            security: true
            provider: chain_provider
            stateless: true
            guard:
                authenticators:
                    - 'AppBundle\Security\TelegramUpdateAuthenticator'
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
